name: build

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11.0]
        go: [1.15, 1.17, 1.18]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: '${{ matrix.go }}'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: make

    - name: Test
      run: make test
